// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f1b8a42a-dced-41d5-a71e-f6ab89fa19b7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AAHMNlRzV",
    "aws_user_pools_web_client_id": "6v03932b7ihlhvhrl8mfpso3n1",
    "aws_appsync_graphqlEndpoint": "https://dgf6e7reenaupmbpvpesncuqge.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
